### ISSUE TITLE
Win10 花屏

### ISSUE THREAD

**Issue by ArArgon** [CHINA-JIGE/Shoot-The-Chicken-3D#4]
如图
![default](https://user-images.githubusercontent.com/31000844/29711649-6f9d527e-89c8-11e7-8690-306ecd90e0a3.PNG)

**Comment by CHINA-JIGE** [comment]
木有win10不知怎么修- -但是估计解决方案是在Renderer.cpp里面调一下mFunction_AdjustWindowSize()里面的窗口固定大小吧，win10控制台变了，有点棘手

**Comment by ArArgon** [comment]
# 我现在把mFunction_AdjustWindowSize()改了改
![qq 20170916114419](https://user-images.githubusercontent.com/31000844/30508894-77dc12be-9ad4-11e7-8a92-ad939a73c10d.png)
![qq 20170916114442](https://user-images.githubusercontent.com/31000844/30508895-7813e108-9ad4-11e7-9791-6b8742284832.png)

**Comment by ArArgon** [comment]
但是还是有点怪

**Comment by CHINA-JIGE** [comment]
因为其实这个窗口的像素大小有点hack的成分在里面...算好了每个字符占3x5像素然后强行算出窗口大小，所以可能win10的这些有变化就这样子了,可以debug一下GetSystemMetric()的那些值吧

**Comment by SnailSword** [comment]
会不会是字体的问题导致的？

**Comment by zhongyang219** [comment]
在窗口标题栏点击鼠标右键，选择“属性”，勾选“使用旧版控制台”就可以了。
![image](https://user-images.githubusercontent.com/30562462/54894279-cd02a480-4ef4-11e9-9424-6f882f27b468.png)
